### ISSUE TITLE
CI/CDワークフローのTDD原則に基づく改善

### ISSUE THREAD

**Issue by ayutaz** [ayutaz/piper#60]
## 概要

現在のCI/CDワークフローは機能していますが、TDD原則に基づいて改善の余地があります。

## 現状の課題

1. **巨大で複雑なワークフロー**
   - `test-multilingual-tts.yml`: 769行
   - `dev-daily-release.yml`: 1077行

2. **実装の詳細への依存**
   - 内部ディレクトリ構造のチェック
   - ログメッセージの文言依存

3. **責務の混在**
   - ビルド、テスト、リリースが1つのワークフローに混在

### 1. 新しいワークフロー構造

```yaml
build-and-test.yml  # ビルドと基本テストに特化（目標: 200行以内）
release.yml         # リリースプロセスのみ
```

### 2. TDD原則の適用

- **ユーザー視点のテスト**: 実装詳細ではなく、ユーザーが期待する動作をテスト
- **シンプルで明確**: 何をテストしているかが一目で分かる
- **独立性**: 各テストが独立して実行可能

### 3. 段階的な移行

1. 新しいワークフローを追加（既存と並行運用）
2. 安定性を確認（2週間程度）
3. レガシーワークフローを削除

## 期待される効果

- CIの実行時間短縮（目標: 50%削減）
- デバッグが容易
- 新しいテストの追加が簡単
- False Positiveの削減

## 実装例

```yaml
# build-and-test.yml の例
name: Build and Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cmake -B build && cmake --build build
      
  test-basic:
    needs: build
    steps:
      - name: Test - Can start
        run: ./piper --help
      - name: Test - Basic TTS works
        run: echo "Hello" | ./piper --model test.onnx --output test.wav
      - name: Test - Japanese works
        run: echo "こんにちは" | ./piper --model ja.onnx --output ja.wav
```

## 関連PR

- #59 - ファイル整理のPR（ワークフロー改善は含まない）
